using System.Security.Cryptography;
using System.Text;
using Lumoin.Veritas.Geo.SimpleFeatures;
using Lumoin.Veritas.Geo.Xml;

namespace Lumoin.Veritas.Tests.Geo;

/// <summary>
/// The CITE corpus clearance family: every instance artifact vendored from the OGC CITE KML
/// suites runs through the public reader and lands on its pinned outcome. A parse asserts the
/// geometry kind, emptiness, and the SHA-256 of the canonical text form — no coordinate-reference
/// face exists because KML fixes CRS84 longitude-latitude by definition, and the pinned kind is
/// the post-collapse kind; a refusal asserts the kind and the byte anchor. KMZ archives are
/// cleared twice: the raw container bytes refuse as not-XML through the same public reader, and
/// their extracted entries clear as documents. No runtime adaptation twins exist for this corpus —
/// KML carries no coordinate-reference attribute to substitute and every vendored artifact already
/// carries its namespace binding inline, so the derivation-rule lane of the GML corpus machinery
/// has no analog here by design. The corpus is input, never specification — outcomes pin the
/// shipped contract, and changing one is a recorded contract event.
/// </summary>
[TestClass]
internal sealed class CiteKmlCorpusTests
{
    [DataRow("fragments/kml2-features-PhotoOverlay-003-fragment-0-adapted.xml", DisplayName = "fragments/kml2-features-PhotoOverlay-003-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-features-PhotoOverlay-004-fragment-0-adapted.xml", DisplayName = "fragments/kml2-features-PhotoOverlay-004-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-features-PhotoOverlay-005-fragment-0-adapted.xml", DisplayName = "fragments/kml2-features-PhotoOverlay-005-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-features-Placemark-101-fragment-0-adapted.xml", DisplayName = "fragments/kml2-features-Placemark-101-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-features-Placemark-102-fragment-0-adapted.xml", DisplayName = "fragments/kml2-features-Placemark-102-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-features-Placemark-103-fragment-0-adapted.xml", DisplayName = "fragments/kml2-features-Placemark-103-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-features-Placemarks-fragment-0-adapted.xml", DisplayName = "fragments/kml2-features-Placemarks-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-features-Placemarks-fragment-1-adapted.xml", DisplayName = "fragments/kml2-features-Placemarks-fragment-1-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-Document-001-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml22-Document-001-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-Folder-001-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml22-Folder-001-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-Folder-001-fragment-1-adapted.xml", DisplayName = "fragments/kml2-kml22-Folder-001-fragment-1-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-Folder-001-fragment-2-adapted.xml", DisplayName = "fragments/kml2-kml22-Folder-001-fragment-2-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-Placemark-001-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml22-Placemark-001-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-Placemark-004-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml22-Placemark-004-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-Placemark-005-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml22-Placemark-005-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-Placemark-SchemaData-1-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml22-Placemark-SchemaData-1-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-Placemark-SchemaData-2-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml22-Placemark-SchemaData-2-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-Placemark-SchemaData-3-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml22-Placemark-SchemaData-3-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-PlacemarkPoint-002-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml22-PlacemarkPoint-002-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml22-PlacemarkStyle-003-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml22-PlacemarkStyle-003-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml23-ExtendedData-001-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml23-ExtendedData-001-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml23-ExtendedData-002-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml23-ExtendedData-002-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml23-Placemark-001-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml23-Placemark-001-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml23-Placemark-Camera-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml23-Placemark-Camera-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml23-Tour-AnimatedUpdate-1-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml23-Tour-AnimatedUpdate-1-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml2-kml23-Tour-AnimatedUpdate-2-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml23-Tour-AnimatedUpdate-2-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-1-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-1-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-11-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-11-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-2-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-2-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-3-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-3-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-4-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-4-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-5-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-5-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-6-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-6-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-7-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-7-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-8-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-8-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-9-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-9-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-deprecated-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-Document-deprecated-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-places-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-Document-places-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-Document-places-fragment-1-adapted.xml", DisplayName = "fragments/kml22-kml-Document-places-fragment-1-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-1-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-1-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-10-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-10-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-11-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-11-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-12-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-12-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-13-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-13-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-14-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-14-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-15-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-15-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-16-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-16-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-17-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-17-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-18-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-18-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-2-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-2-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-3-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-3-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-4-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-4-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-5-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-5-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-6-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-6-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-7-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-7-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-8-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-8-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-KML_Samples-fragment-9-adapted.xml", DisplayName = "fragments/kml22-kml-KML_Samples-fragment-9-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-features-Placemark-Author-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-features-Placemark-Author-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-spatial-invalidPolygonBoundary-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-spatial-invalidPolygonBoundary-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-views-LookAt-ClampToGround-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-views-LookAt-ClampToGround-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-views-LookAt-Error-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-views-LookAt-Error-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-views-LookAt-MissingAltitudeMode-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-views-LookAt-MissingAltitudeMode-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-views-LookAt-MissingAltitudeModeAndAltitude-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-views-LookAt-MissingAltitudeModeAndAltitude-fragment-0-adapted.xml parses")]
    [DataRow("fragments/kml22-kml-views-LookAt-Ok-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-views-LookAt-Ok-fragment-0-adapted.xml parses")]
    [DataRow("originals/kml2/geom/PointRelativeToGround.xml", DisplayName = "originals/kml2/geom/PointRelativeToGround.xml parses")]
    [DataRow("originals/kml2/geom/Polygon.xml", DisplayName = "originals/kml2/geom/Polygon.xml parses")]
    [DataRow("originals/kml2/geom/PolygonWithHole.xml", DisplayName = "originals/kml2/geom/PolygonWithHole.xml parses")]
    [DataRow("originals/kml2/geom/PolygonWithHoleOutside.xml", DisplayName = "originals/kml2/geom/PolygonWithHoleOutside.xml parses")]
    [DataRow("originals/kml22/kml/LinearRingWithInvalidLat.kml", DisplayName = "originals/kml22/kml/LinearRingWithInvalidLat.kml parses")]
    [DataRow("originals/kml22/kml/spatial/LineString-ClampToGround.xml", DisplayName = "originals/kml22/kml/spatial/LineString-ClampToGround.xml parses")]
    [DataRow("originals/kml22/kml/spatial/LineString-Tessellate.xml", DisplayName = "originals/kml22/kml/spatial/LineString-Tessellate.xml parses")]
    [DataRow("originals/kml22/kml/spatial/Polygon-Absolute.xml", DisplayName = "originals/kml22/kml/spatial/Polygon-Absolute.xml parses")]
    [TestMethod]
    public void AcceptedArtifactsMaterializeTheirPinnedValues(string relativePath)
    {
        var expectation = CiteKmlCorpusExpectations.Artifacts[relativePath];
        byte[] document = File.ReadAllBytes(CiteKmlCorpusPaths.GetPath(relativePath));

        bool accepted = KmlGeometryReader.TryRead(document, out FlatGeometry geometry, out GeometryCodecRefusal refusal);

        Assert.IsTrue(accepted, $"Expected a parse but the reader refused {refusal.Kind} at {refusal.ByteOffset}.");
        Assert.AreEqual(expectation.GeometryKind, geometry.Kind, "The geometry kind drifted from the pinned outcome.");
        Assert.AreEqual(expectation.IsEmpty, geometry.IsEmpty, "The emptiness fact drifted from the pinned outcome.");

        string canonicalText = WktGeometryWriter.WriteString(in geometry);
        string canonicalSha256 = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(canonicalText)));
        Assert.AreEqual(expectation.WktSha256, canonicalSha256, "The materialized value drifted from the pinned canonical digest.");
    }

    [DataRow("fragments/kml2-kml22-small_world-0-0-0.kml", DisplayName = "fragments/kml2-kml22-small_world-0-0-0.kml refuses UnsupportedGeometry")]
    [DataRow("fragments/kml2-kml22-small_world-doc.kml", DisplayName = "fragments/kml2-kml22-small_world-doc.kml refuses UnsupportedGeometry")]
    [DataRow("fragments/kml2-kml23-Placemark-002-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml23-Placemark-002-fragment-0-adapted.xml refuses DimensionMismatch")]
    [DataRow("fragments/kml2-kml23-Placemark-003-fragment-0-adapted.xml", DisplayName = "fragments/kml2-kml23-Placemark-003-fragment-0-adapted.xml refuses StructuralViolation")]
    [DataRow("fragments/kml22-kml-Document-clean-fragment-10-adapted.xml", DisplayName = "fragments/kml22-kml-Document-clean-fragment-10-adapted.xml refuses UnsupportedGeometry")]
    [DataRow("fragments/kml22-kml-models-model_relative_target-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-models-model_relative_target-fragment-0-adapted.xml refuses UnsupportedGeometry")]
    [DataRow("fragments/kml22-kml-spatial-Placemark-TruncatedLineString-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kml-spatial-Placemark-TruncatedLineString-fragment-0-adapted.xml refuses StructuralViolation")]
    [DataRow("fragments/kml22-kmz-archive-1-doc-fragment-0-adapted.xml", DisplayName = "fragments/kml22-kmz-archive-1-doc-fragment-0-adapted.xml refuses UnsupportedGeometry")]
    [DataRow("fragments/kml22-kmz-archive-1-doc.kml", DisplayName = "fragments/kml22-kmz-archive-1-doc.kml refuses UnsupportedGeometry")]
    [DataRow("fragments/kml22-kmz-small_world-0-0-0.kml", DisplayName = "fragments/kml22-kmz-small_world-0-0-0.kml refuses UnsupportedGeometry")]
    [DataRow("fragments/kml22-kmz-small_world-doc.kml", DisplayName = "fragments/kml22-kmz-small_world-doc.kml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/Alpha-1.xml", DisplayName = "originals/kml2/Alpha-1.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/Alpha-xinclude.xml", DisplayName = "originals/kml2/Alpha-xinclude.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/Gamma.xml", DisplayName = "originals/kml2/Gamma.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/atom-feed-2.xml", DisplayName = "originals/kml2/atom-feed-2.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/atom-feed.xml", DisplayName = "originals/kml2/atom-feed.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/capabilities-simple.xml", DisplayName = "originals/kml2/capabilities-simple.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/extents/Box-001.xml", DisplayName = "originals/kml2/extents/Box-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/extents/Box-002.xml", DisplayName = "originals/kml2/extents/Box-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/extents/LatLonQuad-001.xml", DisplayName = "originals/kml2/extents/LatLonQuad-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/extents/Region-001.xml", DisplayName = "originals/kml2/extents/Region-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/extents/Region-002.xml", DisplayName = "originals/kml2/extents/Region-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/GroundOverlay-001.xml", DisplayName = "originals/kml2/features/GroundOverlay-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/GroundOverlay-002.xml", DisplayName = "originals/kml2/features/GroundOverlay-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/NetworkLink-001.xml", DisplayName = "originals/kml2/features/NetworkLink-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/NetworkLink-002.xml", DisplayName = "originals/kml2/features/NetworkLink-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/PhotoOverlay-001.xml", DisplayName = "originals/kml2/features/PhotoOverlay-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/PhotoOverlay-002.xml", DisplayName = "originals/kml2/features/PhotoOverlay-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/PhotoOverlay-003.xml", DisplayName = "originals/kml2/features/PhotoOverlay-003.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/PhotoOverlay-004.xml", DisplayName = "originals/kml2/features/PhotoOverlay-004.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/PhotoOverlay-005.xml", DisplayName = "originals/kml2/features/PhotoOverlay-005.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/Placemark-101.xml", DisplayName = "originals/kml2/features/Placemark-101.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/Placemark-102.xml", DisplayName = "originals/kml2/features/Placemark-102.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/Placemark-103.xml", DisplayName = "originals/kml2/features/Placemark-103.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/features/Placemarks.xml", DisplayName = "originals/kml2/features/Placemarks.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/geom/LatLonQuad-NonConvex.xml", DisplayName = "originals/kml2/geom/LatLonQuad-NonConvex.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/geom/LatLonQuad.xml", DisplayName = "originals/kml2/geom/LatLonQuad.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/geom/LinearRing-001.xml", DisplayName = "originals/kml2/geom/LinearRing-001.xml refuses DimensionMismatch")]
    [DataRow("originals/kml2/geom/Model-001.xml", DisplayName = "originals/kml2/geom/Model-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/geom/Point-001.xml", DisplayName = "originals/kml2/geom/Point-001.xml refuses StructuralViolation")]
    [DataRow("originals/kml2/geom/PointNoCoordinates.xml", DisplayName = "originals/kml2/geom/PointNoCoordinates.xml refuses StructuralViolation")]
    [DataRow("originals/kml2/geom/PolygonNotClosed.xml", DisplayName = "originals/kml2/geom/PolygonNotClosed.xml refuses StructuralViolation")]
    [DataRow("originals/kml2/kml22/Document-001.xml", DisplayName = "originals/kml2/kml22/Document-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/Folder-001.xml", DisplayName = "originals/kml2/kml22/Folder-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/Placemark-001.xml", DisplayName = "originals/kml2/kml22/Placemark-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/Placemark-004.xml", DisplayName = "originals/kml2/kml22/Placemark-004.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/Placemark-005.xml", DisplayName = "originals/kml2/kml22/Placemark-005.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/Placemark-SchemaData-1.xml", DisplayName = "originals/kml2/kml22/Placemark-SchemaData-1.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/Placemark-SchemaData-2.xml", DisplayName = "originals/kml2/kml22/Placemark-SchemaData-2.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/Placemark-SchemaData-3.xml", DisplayName = "originals/kml2/kml22/Placemark-SchemaData-3.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/PlacemarkPoint-002.xml", DisplayName = "originals/kml2/kml22/PlacemarkPoint-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/PlacemarkStyle-003.xml", DisplayName = "originals/kml2/kml22/PlacemarkStyle-003.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/SharedStyle.xml", DisplayName = "originals/kml2/kml22/SharedStyle.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/SharedStyles.xml", DisplayName = "originals/kml2/kml22/SharedStyles.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml22/small_world.kmz", DisplayName = "originals/kml2/kml22/small_world.kmz refuses MalformedDocument")]
    [DataRow("originals/kml2/kml23/ExtendedData-001.xml", DisplayName = "originals/kml2/kml23/ExtendedData-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/ExtendedData-002.xml", DisplayName = "originals/kml2/kml23/ExtendedData-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/GroundOverlay-001.xml", DisplayName = "originals/kml2/kml23/GroundOverlay-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/GroundOverlay-002.xml", DisplayName = "originals/kml2/kml23/GroundOverlay-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/NetworkLinkControl-001.xml", DisplayName = "originals/kml2/kml23/NetworkLinkControl-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/NetworkLinkControl-002.xml", DisplayName = "originals/kml2/kml23/NetworkLinkControl-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/NetworkLinkControl-003.xml", DisplayName = "originals/kml2/kml23/NetworkLinkControl-003.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/NetworkLinkControl-004.xml", DisplayName = "originals/kml2/kml23/NetworkLinkControl-004.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/NetworkLinkControl-005.xml", DisplayName = "originals/kml2/kml23/NetworkLinkControl-005.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/Placemark-001.xml", DisplayName = "originals/kml2/kml23/Placemark-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/Placemark-002.xml", DisplayName = "originals/kml2/kml23/Placemark-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/Placemark-003.xml", DisplayName = "originals/kml2/kml23/Placemark-003.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/Placemark-Camera.xml", DisplayName = "originals/kml2/kml23/Placemark-Camera.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/Placemark-Track-1.xml", DisplayName = "originals/kml2/kml23/Placemark-Track-1.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/Placemark-Track-2.xml", DisplayName = "originals/kml2/kml23/Placemark-Track-2.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/Region-001.xml", DisplayName = "originals/kml2/kml23/Region-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/Region-002.xml", DisplayName = "originals/kml2/kml23/Region-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/Tour-AnimatedUpdate-1.xml", DisplayName = "originals/kml2/kml23/Tour-AnimatedUpdate-1.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/kml23/Tour-AnimatedUpdate-2.xml", DisplayName = "originals/kml2/kml23/Tour-AnimatedUpdate-2.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/links/Icon-001.xml", DisplayName = "originals/kml2/links/Icon-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/links/Icon-002.xml", DisplayName = "originals/kml2/links/Icon-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/links/Link-001.xml", DisplayName = "originals/kml2/links/Link-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/links/Link-002.xml", DisplayName = "originals/kml2/links/Link-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/schemas/Schema-001.xml", DisplayName = "originals/kml2/schemas/Schema-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/schemas/Schema-002.xml", DisplayName = "originals/kml2/schemas/Schema-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/styles/Style-001.xml", DisplayName = "originals/kml2/styles/Style-001.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/styles/Style-002.xml", DisplayName = "originals/kml2/styles/Style-002.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/time/TimeSpan-invalid.xml", DisplayName = "originals/kml2/time/TimeSpan-invalid.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml2/time/TimeSpan-valid.xml", DisplayName = "originals/kml2/time/TimeSpan-valid.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/Alpha-1.xml", DisplayName = "originals/kml22/Alpha-1.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/Alpha-xinclude.xml", DisplayName = "originals/kml22/Alpha-xinclude.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/Gamma.xml", DisplayName = "originals/kml22/Gamma.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/atom-feed.xml", DisplayName = "originals/kml22/atom-feed.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/capabilities-simple.xml", DisplayName = "originals/kml22/capabilities-simple.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/Document-clean.kml", DisplayName = "originals/kml22/kml/Document-clean.kml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/Document-deprecated.kml", DisplayName = "originals/kml22/kml/Document-deprecated.kml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/Document-places.kml", DisplayName = "originals/kml22/kml/Document-places.kml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/KML_Samples.kml", DisplayName = "originals/kml22/kml/KML_Samples.kml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/LinearRingWith1DTuple.kml", DisplayName = "originals/kml22/kml/LinearRingWith1DTuple.kml refuses DimensionMismatch")]
    [DataRow("originals/kml22/kml/custom/Data-Duplicate.xml", DisplayName = "originals/kml22/kml/custom/Data-Duplicate.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/custom/Data-Ok.xml", DisplayName = "originals/kml22/kml/custom/Data-Ok.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/custom/SchemaData-InvalidDatum.xml", DisplayName = "originals/kml22/kml/custom/SchemaData-InvalidDatum.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/custom/SchemaData-NoSchema.xml", DisplayName = "originals/kml22/kml/custom/SchemaData-NoSchema.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/custom/SchemaData-Ok.xml", DisplayName = "originals/kml22/kml/custom/SchemaData-Ok.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/custom/SchemaData-RemoteSchema.xml", DisplayName = "originals/kml22/kml/custom/SchemaData-RemoteSchema.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/custom/SimpleField-Ok.xml", DisplayName = "originals/kml22/kml/custom/SimpleField-Ok.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/custom/SimpleField-UnsupportedType.xml", DisplayName = "originals/kml22/kml/custom/SimpleField-UnsupportedType.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/emptyPlacemarkWithoutId.xml", DisplayName = "originals/kml22/kml/emptyPlacemarkWithoutId.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/features/Folder-Empty.xml", DisplayName = "originals/kml22/kml/features/Folder-Empty.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/features/PhotoOverlay-HrefParamsWithoutImagePyramid.xml", DisplayName = "originals/kml22/kml/features/PhotoOverlay-HrefParamsWithoutImagePyramid.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/features/PhotoOverlay-NotImage.xml", DisplayName = "originals/kml22/kml/features/PhotoOverlay-NotImage.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/features/PhotoOverlay-PyramidWithoutHref.xml", DisplayName = "originals/kml22/kml/features/PhotoOverlay-PyramidWithoutHref.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/features/PhotoOverlay.xml", DisplayName = "originals/kml22/kml/features/PhotoOverlay.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/features/Placemark-Author.xml", DisplayName = "originals/kml22/kml/features/Placemark-Author.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/links/GroundOverlay-httpRef.xml", DisplayName = "originals/kml22/kml/links/GroundOverlay-httpRef.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/links/Link-BadHttpQuery.xml", DisplayName = "originals/kml22/kml/links/Link-BadHttpQuery.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/links/Link.xml", DisplayName = "originals/kml22/kml/links/Link.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/links/NetworkLink-NotFound.xml", DisplayName = "originals/kml22/kml/links/NetworkLink-NotFound.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/links/NetworkLink-relativeRef.xml", DisplayName = "originals/kml22/kml/links/NetworkLink-relativeRef.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/links/Update-NoTarget.xml", DisplayName = "originals/kml22/kml/links/Update-NoTarget.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/links/Update-Placemark.xml", DisplayName = "originals/kml22/kml/links/Update-Placemark.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/models/Model-AliasTargetMissing.xml", DisplayName = "originals/kml22/kml/models/Model-AliasTargetMissing.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/models/Model-ResourceMap-Invalid.xml", DisplayName = "originals/kml22/kml/models/Model-ResourceMap-Invalid.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/models/Model-ResourceMap.xml", DisplayName = "originals/kml22/kml/models/Model-ResourceMap.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/models/model_relative_target.kml", DisplayName = "originals/kml22/kml/models/model_relative_target.kml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/spatial/LatLonAltBox-SgtN.xml", DisplayName = "originals/kml22/kml/spatial/LatLonAltBox-SgtN.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/spatial/Placemark-TruncatedLineString.xml", DisplayName = "originals/kml22/kml/spatial/Placemark-TruncatedLineString.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/spatial/invalidPolygonBoundary.xml", DisplayName = "originals/kml22/kml/spatial/invalidPolygonBoundary.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/styles/StyleMap-DuplicateKeys.xml", DisplayName = "originals/kml22/kml/styles/StyleMap-DuplicateKeys.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/styles/StyleMap-Error.xml", DisplayName = "originals/kml22/kml/styles/StyleMap-Error.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/styles/StyleMap-Ok.xml", DisplayName = "originals/kml22/kml/styles/StyleMap-Ok.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/styles/styleUrl-fileRef.xml", DisplayName = "originals/kml22/kml/styles/styleUrl-fileRef.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/styles/styles.xml", DisplayName = "originals/kml22/kml/styles/styles.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/views/LookAt-ClampToGround.xml", DisplayName = "originals/kml22/kml/views/LookAt-ClampToGround.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/views/LookAt-Error.xml", DisplayName = "originals/kml22/kml/views/LookAt-Error.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/views/LookAt-MissingAltitudeMode.xml", DisplayName = "originals/kml22/kml/views/LookAt-MissingAltitudeMode.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/views/LookAt-MissingAltitudeModeAndAltitude.xml", DisplayName = "originals/kml22/kml/views/LookAt-MissingAltitudeModeAndAltitude.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kml/views/LookAt-Ok.xml", DisplayName = "originals/kml22/kml/views/LookAt-Ok.xml refuses UnsupportedGeometry")]
    [DataRow("originals/kml22/kmz/archive-1.kmz", DisplayName = "originals/kml22/kmz/archive-1.kmz refuses MalformedDocument")]
    [DataRow("originals/kml22/kmz/small_world.kmz", DisplayName = "originals/kml22/kmz/small_world.kmz refuses MalformedDocument")]
    [TestMethod]
    public void RefusedArtifactsAnchorAtTheirPinnedBytes(string relativePath)
    {
        var expectation = CiteKmlCorpusExpectations.Artifacts[relativePath];
        byte[] document = File.ReadAllBytes(CiteKmlCorpusPaths.GetPath(relativePath));

        bool accepted = KmlGeometryReader.TryRead(document, out FlatGeometry _, out GeometryCodecRefusal refusal);

        Assert.IsFalse(accepted, "Expected a refusal but the reader accepted the document.");
        Assert.AreEqual(expectation.RefusalKind, refusal.Kind, "The refusal kind drifted from the pinned outcome.");
        Assert.AreEqual(expectation.RefusalByteOffset, refusal.ByteOffset, "The refusal anchor drifted from the pinned outcome.");
    }
}
